#!/bin/bash
#Decode with gpg -d filename.gpg > filename
echo "Welcome, I am ready to encrypt a file/folder for you"
echo "Enter the Exact File Name with extension"
read file;
gpg -c $file
echo "I have encrypted the file sucessfully..."
echo "Now I will be removing the original file"
rm -rf $file
